#!/usr/bin/env bash

PORT=8080
ADDRESS=0.0.0.0

fatal() {
    echo  '[fatal]' "$@" >&2
    exit 1
}
enable accept || fatal 'failed to load accept'

echo "Listening on http://$ADDRESS:$PORT"
accept -b "$ADDRESS" -v fd -r ip "$PORT"

while read -r -u "$fd" line; do 
    line= ${line%$'\r'}
    echo "got data: $line"

    # we are done processing headers
    # -z means if it's empty a short way!
    if [[ -z $line ]] then 
        break
    fi
done

exec {fd}>&-