#!/usr/bin/env bash

PORT=8080
ADDRESS=0.0.0.0

fatal() {
    echo  '[fatal]' "$@" >&2
    exit 1
}
enable accept || fatal 'failed to load accept'

echo "Listening on http://$ADDRESS:$PORT"
accept -b "$ADDRESS" -v fd -r ip "$PORT"

while read -r -u "$fd" line; do 
    line=${line%$'\r'}
    echo "got data: $line"

    # we are done processing headers
    # -z means if it's empty a short way!
    if [[ -z $line ]]; then 
        break
    fi
done

# if we are here, we should reply to the caller so we need to write to the file scripter
printf 'HTTP/1.1 200 ok\r\n' >&"$fd"
printf 'Content-Type: text/plain\r\n' >&"$fd"
printf '\r\n' >&"$fd"
cat file.txt >&"$fd"

exec {fd}>&-