#!/usr/bin/env bash

s="GET /foo.txt HTTP/1.1
Host: localhost:8080
User-Agent: curl/8.7.1
Accept: */*"

parse-request () {
    # where we store the meta data: method, version, path, ...
    declare -gA REQ_INFO=()
    declare -gA REQ_HEADERS=()

    local state='status'
    local line
    while read -r line; do 
        echo "processing line: $line"

        case "$state" in
                'status')
                        # parse the status line
                        local method path version
                        read -r method path version <<< "$line"
                        REQ_INFO[method]=$method
                        REQ_INFO[path]=$path 
                        REQ_INFO[version]=$version
                        state='headers'
                        ;;
                'headers')
                        if [[ -z $line ]]; then 
                            break
                        fi
                        # parse the headers
                        local key value
                        IFS=: read -r key value <<< "$line"
                        # make the key lower case, headers are case insensetive
                        key=${key,,}
                        value=${value# *}
                        REQ_HEADERS[$key]=$value
                        ;;
                'body')
                        # pase the body
                        fatal 'body parsing not supported'
                        ;;
        esac
    done
}

parse-request <<< "$s"

echo "REQ_INFO"
for key in "${!REQ_INFO[@]}"; do
    value=${REQ_INFO[$key]}
    echo "$key => $value"
done

echo "REQ_HEADERS"
for key in "${!REQ_HEADERS[@]}"; do
    value=${REQ_HEADERS[$key]}
    echo "$key => $value"
done